SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SCORE_AMOUNT = 10

POWER_UP_SIZE = 20
POWER_UP_SPAWN_RATE = 0.002
POWER_UP_DURATION = 5
BOMB_EQUIP_DURATION = 10


SHIELD_COLOR = "blue"
SPEED_COLOR = "green"
BOMB_COLOR = "red"